### ISSUE TITLE
Parsing does not Terminate

### ISSUE THREAD

**Issue by taiseiKMC** [dinosaure/multipart_form#25]
When a requested body is incomplete, `Multipart_form.parse` sometimes seems to go into an infinite loop

I tried this below code in Multipart_form:v0.3.0
```ocaml

let req =
  {|--------------------------eb790219f130e103
Content-Disposition: form-data; name="text"

default
--------------------------eb790219f130e103
Content-Disposition: form-data; name="file1"; filename="a.html"
Content-Type: text/html

<!DOCTYPE html><title>Content of a.html.</title>

--------------------------eb790219f130e103
Content-Disposition: form-data; name="file2"; filename="a.txt"
Content-Type: text/plain

Conten|}

let run =
  let content_type = Result.get_ok @@ Multipart_form.Content_type.of_string
       "multipart/form-data; \
        boundary=------------------------eb790219f130e103\r\n" in
  let body_stream = Lwt_stream.return req in
  let `Parse th, _ = Multipart_form_lwt.stream ~identify:(fun a -> ()) body_stream content_type in
  Lwt.bind th (fun res -> (match res with | Ok _ -> () | Error (`Msg str) -> failwith str); Lwt.return_unit)

let () = Lwt_main.run run
```

**Comment by dinosaure** [comment]
Hmmhmm, I can look more closely but it seems that you example was truncated - and it did not finish with the expected `end-of-boundary`.

But yeah, the process should not do an infinite loop and it should have a mechanism to stop and return an error at least. Currently, we found a bug about that on the `mrmime` parser too and I did not (yet) patch-back into this library. 

Then, I'm currently on vacation but I will look this bug in few weeks. Thanks for your report.

**Comment by dinosaure** [comment]
Hmmhmm, I just tried to reproduce your case with #27 and it seems that everything is fine. I tested with and without CRLF (I believe that your request as with CRLF but GitHub does not print them) and I got expected results. Note that even if the close delimiter is missing, we consider the request as valid (we discovered many times that the close delimiter is missing).
